networks:
    nurtricenter-net:
        external: true

services:
    commercial-api:
        container_name: commercial-api
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - commercial_vendor:/var/www/html/vendor
        ports:
            - 9092:80
        networks:
            - nurtricenter-net
        depends_on:
            commercial-db:
                condition: service_healthy
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: commercial-db
            DB_PORT: 5432
            DB_DATABASE: commercial
            DB_USERNAME: commercial
            DB_PASSWORD: commercial123
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_PORT: 5672
            RABBITMQ_USER: admin
            RABBITMQ_PASSWORD: admin
            RABBITMQ_VHOST: /
            APP_ENV: local
            APP_DEBUG: 'true'
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:80/api/commercial/catalogs']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    commercial-db:
        container_name: commercial-db
        image: postgres:17
        ports:
            - 5435:5432
        volumes:
            - commercial_db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: commercial
            POSTGRES_PASSWORD: commercial123
            POSTGRES_DB: commercial
        networks:
            - nurtricenter-net
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 10s

volumes:
    commercial_vendor:
    commercial_db_data:
