services:
  commercial-api:
    container_name: commercial-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - commercial_vendor:/var/www/html/vendor
    ports:
      - 9092:80
    networks:
      - nurtricenter_network
    depends_on:
      commercial-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: commercial-db
      DB_PORT: ${POSTGRES_PORT}
      DB_DATABASE: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: commercial
      RABBITMQ_PASSWORD: commercial123
      RABBITMQ_VHOST: /
      APP_ENV: local
      APP_DEBUG: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/commercial/catalogs"]
      interval: 3600s
      timeout: 10s
      retries: 3
      start_period: 40s

  commercial-db:
    container_name: commercial-db
    image: postgres:15
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - commercial_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - nurtricenter_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 3600s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3.13.7-management
    container_name: commercial-rabbitmq
    ports:
      - "5672:5672"  # Puerto AMQP
      - "15672:15672" # UI de gestión
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - commercial_rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: commercial
      RABBITMQ_DEFAULT_PASS: commercial123
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_management load_definitions \"/etc/rabbitmq/definitions.json\""
    networks:
      - nurtricenter_network
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  commercial_vendor:
  commercial_postgres_data:
  commercial_rabbitmq_data:

networks:
  nurtricenter_network:
