name: Deploy

on:
  push:
    branches: [ main ]  # O la rama que prefieras (develop, master, etc.)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, curl, zip

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Run tests
      run: php artisan test --testsuite=Unit --exclude-group skip-ci
        
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
      
    - name: Deploy to production
      run: |
        ssh ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }} "/home/deployer/deploy.sh"
